import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  dsSidebar: [{ type: 'autogenerated', dirName: 'subject/DS' }],
  osSidebar: [{ type: 'autogenerated', dirName: 'subject/OS' }],
  cnSidebar: [{ type: 'autogenerated', dirName: 'subject/CN' }],
  coaSidebar: [{ type: 'autogenerated', dirName: 'subject/COA' }],
  vueSidebar: [{ type: 'autogenerated', dirName: 'framework/vue' }],
  reactSidebar: [{ type: 'autogenerated', dirName: 'framework/react' }],
  otherSidebar: [{ type: 'autogenerated', dirName: 'other' }],
  gameSidebar: [{ type: 'autogenerated', dirName: 'entertainment/game' }],
  musicSidebar: [{ type: 'autogenerated', dirName: 'entertainment/music' }],
  animationSidebar: [{ type: 'autogenerated', dirName: 'entertainment/animation' }],
  // ... other sidebars




  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
